<?php

/**
 * @file
 * Implements hook_theme().
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Url;

/**
 * Register template files.
 */
function koval_theme($existing, $type, $theme, $path) : array {

  return [
    'koval-guestbook-page' => [
      'variables' => [
        'form' => NULL,
        'reviews' => NULL,
        'pager' => NULL,
      ],
    ],
    'koval_review' => [
      'template' => 'koval_review',
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_koval_review(&$variables) {
  // Helpful $content variable for templates.
  $variables['content'] = [];

  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  /** @var \Drupal\guest_book\Entity\GuestBook $entity */
  $entity = $variables['elements']['#koval_review'];

  // Add control button.
  $variables['button'] = [
    '#type' => 'link',
    '#title' => 'Manage',
    '#url' => Url::fromRoute('entity.koval_review.edit', ['koval_review' => $entity->id()],),
  ];

  // Add default image.
  if (count($variables['content']['avatar']) <= 3) {
    $variables['content']['avatar'] = [
      '#theme' => 'image',
      '#uri' => '/modules/custom/koval/files/anonim_user_icon.png',
      '#attributes' => [
        'alt' => 'picture',
        'width' => 150,
        'height' => 150,
      ],
    ];
  }

  $variables['#attached']['library'][] = 'koval/guestbook.reviews';

}
